#!/usr/bin/env bash
set -euo pipefail
echo "python3 -m pip install --no-cache-dir --user \\"
comm -13 /opt/baseline_pip_user.txt <(python3 -m pip list --user --format=freeze | sort) \
  | sed 's/==.*$//' \
  | sed 's/$/ \\/'
echo ""
